[package]
name = "blockchain_cli"
version = "0.1.0"
authors = ["bashhack (Marc Laughton) <info@marclaughton.com>"]
edition = "2018"

[dependencies]
time = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
sha2 = "*"